# Generated by Django 5.0 on 2024-01-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_filesandfolders_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesandfolders',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='filesandfolders',
            name='uploaded_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
