# Generated by Django 5.0 on 2024-01-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_filesandfolders_file_filesandfolders_uploaded_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesandfolders',
            name='link',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
