# Generated by Django 5.0 on 2024-02-02 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_filesandfolders_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='filesandfolders',
            name='file_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='filesandfolders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
