# Generated by Django 5.0 on 2024-02-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_filesandfolders_file_size_alter_filesandfolders_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesandfolders',
            name='last_download',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filesandfolders',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
